#syntax=docker/dockerfile:1.4

FROM aseprite-upstream AS aseprite
FROM toolkit

# Install Aseprite
WORKDIR /opt/aseprite/bin
COPY --from=aseprite /opt/aseprite/bin .
RUN chmod +x /opt/aseprite/bin/aseprite && \
	ln -s /opt/aseprite/bin/aseprite /usr/local/bin/aseprite && \
	ln -s /opt/aseprite/bin/aseprite /usr/local/bin/ase && \
	# Smoke test
	ase --help

WORKDIR /workspace
