name: Build

on:
  workflow_dispatch:
    inputs:
      images-tag:
        required: true
        description: The desired tag postfix to apply to built images
        default: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.git-ref-aseprite || github.ref_name }}

  cancel-in-progress: true

jobs:
  build_and_push:
    name: Build & Push

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker Image
        uses: docker/bake-action@v6
        with:
          targets: |
            toolkit
            with-aseprite
          push: true
          no-cache: true
        env:
          IMAGES_PREFIX: 'ghcr.io/${{ github.repository_owner }}/gdtk:'
          IMAGES_TAG: ${{ github.event.inputs.images-tag }}
